Feature/updated dark
shocknet/wallet pull request #230
Opened 2020-09-02 17:45 UTC by boufni95

2020-09-02 19:09 UTC, danlugo92 requested changes

2020-09-02 19:09 UTC, danlugo92 commented
Bottom bar colors are inverted,

Arturo: White when selected, blue otherwise

Code: Blue when selected, white otherwise

2020-09-02 19:13 UTC, danlugo92 commented
Advanced screen: 

Transactions, channels, peers etc have black text on a dark gray background, non-legible

2020-09-03 16:28 UTC, boufni95 commented on android/settings.gradle
> +project(':react-native-svg').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-svg/android')
removed

2020-09-03 16:28 UTC, boufni95 commented on android/app/src/main/java/com/shockwallet/MainApplication.java
> +import com.horcrux.svg.SvgPackage;
removed

2020-09-03 16:28 UTC, boufni95 commented on android/app/build.gradle
> +    implementation project(':react-native-svg')
removed

2020-09-03 16:28 UTC, boufni95 commented on ios/Podfile
> +  pod 'RNSVG', :path => '../node_modules/react-native-svg'
removed

2020-09-03 16:29 UTC, boufni95 commented on app/screens/MyFeed/index.tsx
> +import React from 'react'
removed

2020-09-03 16:33 UTC, boufni95 commented on app/screens/MyFeed/SetBioDialog.js
> +/* eslint-disable react/jsx-no-bind */
removed

2020-09-03 16:33 UTC, boufni95 commented on app/screens/MyFeed/MetaConfigModal.tsx
> +import React from 'react'
removed

2020-09-03 16:33 UTC, boufni95 commented on app/res/css/index.js
> +  height100: { height: '100%', backgroundColor: '#16191C' },
removed

2020-09-03 19:11 UTC, danlugo92 commented
https://imgur.com/a/3VBa4X7

Few photos showing discrepancy between current dark mode code and Arturo designs

2020-09-03 19:32 UTC, merged